version: '3.8'

services:
  backend:
    build: ./backend # Builds using backend/Docker file
    image: ${DOCKER_USERNAME}/to-do:backend
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    environment:
      - DATA_DIR=/data
    volumes:
      - todo-db:/data

  frontend:
    build: ./frontend # Builds using frontend/Dockerfile
    image: ${DOCKER_USERNAME}/to-do:frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend # starts backend first

volumes:
  todo-db:
    driver: local