# src/backend/schemas.py

from pydantic import BaseModel, ConfigDict
from datetime import datetime
from typing import Optional

# --- Task Schemas ---

# This is the "base" schema.
# Contains fields that are common to both creating and reading.
class TaskBase(BaseModel):
    title: str
    description: Optional[str] = None

# Schema for creating a new task.
# The user only needs to send this data.
class TaskCreate(TaskBase):
    pass

# Schema for reading a task (what you send back to the user).
# It includes the fields that are generated by the database.
class Task(TaskBase):
    id: int
    is_complete: bool
    created_at: datetime
    owner_id: int

    model_config = ConfigDict(from_attributes=True)

class TaskUpdate(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    is_complete: Optional[bool] = None

# --- User Schemas ---

class UserBase(BaseModel):
    username: str

# Schema for creating a new user (input).
class UserCreate(UserBase):
    password: str

# Schema for reading a user (output).
# Notice there is NO password field here. This is for security.
class User(UserBase):
    id: int

    model_config = ConfigDict(from_attributes=True)

# --- Token Schema (for Login) ---

class Token(BaseModel):
    access_token: str
    token_type: str