name: DevOps-Check
on: [push]
jobs:
  test-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a syntax check
        run: bash -n deployment_script.sh
      - name: Simulate a Deployment
        env:
          MY_SECRET: ${{ secrets.PROD_API_KEY }}
        run: |
          echo "Connecting to production server..."
          echo "Using API Key: $MY_SECRET"
