name: "Production-Ping"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ping-test:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Check Version"
        run: node -v

      - name: "Final Message"
        run: echo "Devops Pipline is LIVE!"

      - name: "Debug - List all files"
        run: ls -R

      - name: "Verify config Exists"
        run: ls configs/app-config.yml

      - name: "Security Audit"
        run: |
          echo "Triggered by ${{ github.actor }}"
          echo "Event Type: ${{ github.even_name }}"
          echo "Branch/Tag: ${{ github.ref }}"
